package Sensores;

/**
* Sensores/CorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from proj.idl
* Monday, March 30, 2015 1:23:17 AM BRT
*/

public final class CorHolder implements org.omg.CORBA.portable.Streamable
{
  public Sensores.Cor value = null;

  public CorHolder ()
  {
  }

  public CorHolder (Sensores.Cor initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Sensores.CorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Sensores.CorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Sensores.CorHelper.type ();
  }

}
