package Sensores;


/**
* Sensores/CorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from proj.idl
* Monday, March 30, 2015 1:23:17 AM BRT
*/

abstract public class CorHelper
{
  private static String  _id = "IDL:Sensores/Cor:1.0";

  public static void insert (org.omg.CORBA.Any a, Sensores.Cor that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Sensores.Cor extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Sensores.CorHelper.id (), "Cor");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Sensores.Cor read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CorStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Sensores.Cor value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Sensores.Cor narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Sensores.Cor)
      return (Sensores.Cor)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Sensores._CorStub stub = new Sensores._CorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Sensores.Cor unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Sensores.Cor)
      return (Sensores.Cor)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Sensores._CorStub stub = new Sensores._CorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
