package Sensores;

/**
* Sensores/PhHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from proj.idl
* Monday, March 30, 2015 1:23:17 AM BRT
*/

public final class PhHolder implements org.omg.CORBA.portable.Streamable
{
  public Sensores.Ph value = null;

  public PhHolder ()
  {
  }

  public PhHolder (Sensores.Ph initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Sensores.PhHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Sensores.PhHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Sensores.PhHelper.type ();
  }

}
