package Sensores;


/**
* Sensores/Temperatura.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from proj.idl
* Monday, March 30, 2015 1:23:17 AM BRT
*/

public interface Temperatura extends TemperaturaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Temperatura
