package Sensores;


/**
* Sensores/TemperaturaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from proj.idl
* Monday, March 30, 2015 1:23:17 AM BRT
*/

public abstract class TemperaturaPOA extends org.omg.PortableServer.Servant
 implements Sensores.TemperaturaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getTempValue", new java.lang.Integer (0));
    _methods.put ("setTempValue", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Sensores/Temperatura/getTempValue
       {
         int $result = (int)0;
         $result = this.getTempValue ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // Sensores/Temperatura/setTempValue
       {
         int temp = in.read_long ();
         boolean $result = false;
         $result = this.setTempValue (temp);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Sensores/Temperatura:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Temperatura _this() 
  {
    return TemperaturaHelper.narrow(
    super._this_object());
  }

  public Temperatura _this(org.omg.CORBA.ORB orb) 
  {
    return TemperaturaHelper.narrow(
    super._this_object(orb));
  }


} // class TemperaturaPOA
